version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world-sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-k5c8s8fzhtc8"
s3_prefix = "hello-world-sample"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
